$(document).ready(function(){
        $("#signup-form").validate({
           rules:{
            fname:{
                required:true,
                minlength:0
            },
            Place:{
                required:true,
                minlength:0
            },
            emailAddress:{
                required:true,
                email:true
            },
            gender:{
                required:true
            },
            contact:{
                required:true
            },
            status:{
                required:true
            },
            qualification:{
                required:true
            },
            college:{
                required:true
            },
            Year:{
                required:true
            },
            aboutYou:{
                required:true
            },
            whyDo:{
                required:true
            },
            whatMotivates:{
                required:true
            },
            whereDid:{
                required:true
            },
            checkBox:{
                required:true   
            }
           }
        })
})
